title: "PHP Internals en français"
description: >- # this means to ignore newlines until "baseurl:"
  Suivi des discussions de PHP Internals en Français
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://php-internals.afup.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: afup

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  path: feed
